export let characterColours = {
  "Fox": "orange", 
  "Falco": "blue", 
  "Marth": "purple",
  "Captain Falcon": "red", 
  "Jigglypuff": "pink", 
  "Sheik": "grey", 
  "Peach": "pink", 
  "Dr. Mario": "white", 
  "Luigi": "green", 
  "Ice Climbers": "#83e6ef", 
  "Pikachu": "yellow", 
  "Roy": "#892201", 
  "Samus": "red", 
  "Mario": "red", 
  "Pichu": "#fafe68", 
  "Bowser": "#2c4313", 
  "Donkey Kong": "brown", 
  "Kirby": "pink", 
  "Mewtwo": "#c9c5d5", 
  "Zelda": "pink", 
  "Link": "#22a732", 
  "Young Link": "#22a732", 
  "Mr. Game & Watch": "white", 
  "Yoshi": "#1b901c", 
  "Ganondorf": "#62250c", 
  "Ness": "white"
}
