export let characterColours = {
  "Fox": "#ea9d2a", 
  "Falco": "#3f60f4", 
  "Marth": "#48429e",
  "Captain Falcon": "#d82f2f", 
  "Jigglypuff": "pink", 
  "Sheik": "#e0dedb", 
  "Peach": "pink", 
  "Dr. Mario": "white", 
  "Luigi": "green", 
  "Ice Climbers": "#83e6ef", 
  "Pikachu": "#f6fc3f", 
  "Roy": "#892201", 
  "Samus": "red", 
  "Mario": "#d82f2f", 
  "Pichu": "#fafe68", 
  "Bowser": "#2c4313", 
  "Donkey Kong": "brown", 
  "Kirby": "pink", 
  "Mewtwo": "#c9c5d5", 
  "Zelda": "pink", 
  "Link": "#22a732", 
  "Young Link": "#22a732", 
  "Mr. Game & Watch": "white", 
  "Yoshi": "#59cc55", 
  "Ganondorf": "#62250c", 
  "Ness": "white"
}
